### ISSUE TITLE
Client is not authorized

### ISSUE THREAD

**Issue by aa21** [splashmedia/linkedin-php#4]
PHP Fatal error:  Uncaught exception 'Splash\LinkedIn\Exception' with message '{"error_description":"the client is not authorized","error":"unauthorized_client"}' in /Splash/LinkedIn/Client.php:181

Stack trace:
#0 Splash/LinkedIn/Client.php(101): Splash\LinkedIn\Client->_request('https://www.lin...', Array, 'GET')
#1 /var/www/html/../splash-sample.php(22):

```
Splash\LinkedIn\Client->fetchAccessToken('AQTmDlfPtVWgetP...', 'http://thaifex....')
```
#2 {main}

  thrown in /var/www/html/../LinkedIn/Client.php on line 181

**Comment by equere** [comment]
Hi, I have the same error, have you been able to fix it ?
Regards

**Comment by aa21** [comment]
I don't remember, I think I ended up using some other library. Sorry I can't be of much help.
